### ISSUE TITLE
Make more XDGish

### ISSUE THREAD

**Issue by voxadam** [caarlos0/dotfiles.zsh#121]
While it may not be possible to move _everything_ out of ~/ and into ~/.config, ~/.cache, ~/.local, and whatnot as outlined by the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) it's a noble goal, in my _ever so_ humble opinion. These dotfiles are already so splendidly neat and tidy that I think it would be great if even more cruft could be moved from ~/ and into a structure that not only helps keep one's home directory uncluttered and sleek but allows for a much simpler backup regime.

**Comment by caarlos0** [comment]
So, in your opinion, the right place to put the dotfiles folder is, like, `XDG_CONFIG`? I'm not sure I get what you're saying...

**Comment by eddy-geek** [comment]
Maybe .config/dotfiles makes sense ?

More importantly, the need to symlink stuff to .config exists already with e.g. java/gtkrc-2.0.symlink [on my system I got both ~/.gtkrc-2.0 and ~/.config/gtkrc-2.0 ; not sure which takes precedence]

Other relevant variables, with the "${variable:-default}" syntax:

```
${XDG_DATA_HOME:-$HOME/.local/share}
${XDG_CONFIG_HOME:-$HOME/.config}
${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}
${XDG_CACHE_HOME:-$HOME/.cache}
```

**Comment by caarlos0** [comment]
This is great, but it will increase the complexity of the project A LOT, because it does not have `XDG*`...

That said, I think that at least for now, I'll leave this as is.

If you want to put dotfiles in ~/.config/dotfiles, I think you just need to change [this](https://github.com/caarlos0/dotfiles/blob/master/zsh/zshrc.symlink#L3) variable...
